// CodeSync Pro — Monaco VS Code Themes
'use strict';

const MONACO_THEMES = {
  'vs-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'd4d4d4', background: '1e1e1e' },
      { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'string', foreground: 'ce9178' },
      { token: 'string.escape', foreground: 'd7ba7d' },
      { token: 'string.escape.invalid', foreground: 'f44747' },
      { token: 'string.quote', foreground: 'ce9178' },
      { token: 'string.raw', foreground: 'ce9178' },
      { token: 'string.raw.begin', foreground: 'ce9178' },
      { token: 'string.raw.end', foreground: 'ce9178' },
      { token: 'string.include.identifier', foreground: 'ce9178' },
      { token: 'string.invalid', foreground: 'f44747' },
      { token: 'character', foreground: 'ce9178' },
      { token: 'character.escape', foreground: 'd7ba7d' },
      { token: 'number', foreground: 'b5cea8' },
      { token: 'number.hex', foreground: 'b5cea8' },
      { token: 'number.octal', foreground: 'b5cea8' },
      { token: 'number.binary', foreground: 'b5cea8' },
      { token: 'number.float', foreground: 'b5cea8' },
      { token: 'keyword', foreground: 'c586c0' },
      { token: 'keyword.control', foreground: 'c586c0' },
      { token: 'keyword.directive', foreground: 'c586c0' },
      { token: 'keyword.directive.include', foreground: 'c586c0' },
      { token: 'keyword.directive.include.begin', foreground: 'c586c0' },
      { token: 'keyword.directive.include.end', foreground: 'c586c0' },
      { token: 'keyword.operator', foreground: 'd4d4d4' },
      { token: 'keyword.nullptr', foreground: '569cd6' },
      { token: 'keyword.true', foreground: '569cd6' },
      { token: 'keyword.false', foreground: '569cd6' },
      // Primitive C++ / language types -> VS Code teal
      { token: 'keyword.int', foreground: '4ec9b0' },
      { token: 'keyword.long', foreground: '4ec9b0' },
      { token: 'keyword.char', foreground: '4ec9b0' },
      { token: 'keyword.bool', foreground: '4ec9b0' },
      { token: 'keyword.double', foreground: '4ec9b0' },
      { token: 'keyword.float', foreground: '4ec9b0' },
      { token: 'keyword.void', foreground: '4ec9b0' },
      { token: 'keyword.short', foreground: '4ec9b0' },
      { token: 'keyword.signed', foreground: '4ec9b0' },
      { token: 'keyword.unsigned', foreground: '4ec9b0' },
      { token: 'keyword.auto', foreground: '4ec9b0' },
      { token: 'keyword.wchar_t', foreground: '4ec9b0' },
      { token: 'type', foreground: '4ec9b0' },
      { token: 'type.identifier', foreground: '4ec9b0' },
      { token: 'identifier', foreground: '9cdcfe' },
      { token: 'entity.name.function', foreground: 'dcdcaa' },
      { token: 'entity.name.function.call', foreground: 'dcdcaa' },
      { token: 'support.function', foreground: 'dcdcaa' },
      { token: 'function', foreground: 'dcdcaa' },
      { token: 'variable', foreground: '9cdcfe' },
      { token: 'variable.predefined', foreground: '4fc1ff' },
      { token: 'delimiter', foreground: 'd4d4d4' }
    ],
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#d4d4d4',
      'editorCursor.foreground': '#aeafad',
      'editor.lineHighlightBackground': '#2a2d2e',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#c6c6c6',
      'editor.selectionBackground': '#264f78',
      'editor.inactiveSelectionBackground': '#3a3d41'
    }
  },

  'vs': {
    base: 'vs',
    inherit: true,
    rules: [
      { token: '', foreground: '000000', background: 'ffffff' },
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '008000', fontStyle: 'italic' },
      { token: 'string', foreground: 'a31515' },
      { token: 'string.escape', foreground: 'ee0000' },
      { token: 'string.escape.invalid', foreground: 'cd3131' },
      { token: 'string.quote', foreground: 'a31515' },
      { token: 'string.raw', foreground: 'a31515' },
      { token: 'string.raw.begin', foreground: 'a31515' },
      { token: 'string.raw.end', foreground: 'a31515' },
      { token: 'string.include.identifier', foreground: 'a31515' },
      { token: 'string.invalid', foreground: 'cd3131' },
      { token: 'character', foreground: 'a31515' },
      { token: 'character.escape', foreground: 'ee0000' },
      { token: 'number', foreground: '098658' },
      { token: 'number.hex', foreground: '098658' },
      { token: 'number.float', foreground: '098658' },
      { token: 'keyword', foreground: 'af00db' },
      { token: 'keyword.control', foreground: 'af00db' },
      { token: 'keyword.directive', foreground: 'af00db' },
      { token: 'keyword.directive.include', foreground: 'af00db' },
      { token: 'keyword.directive.include.begin', foreground: 'af00db' },
      { token: 'keyword.directive.include.end', foreground: 'af00db' },
      { token: 'keyword.nullptr', foreground: '0000ff' },
      { token: 'keyword.true', foreground: '0000ff' },
      { token: 'keyword.false', foreground: '0000ff' },
      { token: 'keyword.int', foreground: '267f99' },
      { token: 'keyword.long', foreground: '267f99' },
      { token: 'keyword.char', foreground: '267f99' },
      { token: 'keyword.bool', foreground: '267f99' },
      { token: 'keyword.double', foreground: '267f99' },
      { token: 'keyword.float', foreground: '267f99' },
      { token: 'keyword.void', foreground: '267f99' },
      { token: 'keyword.short', foreground: '267f99' },
      { token: 'keyword.signed', foreground: '267f99' },
      { token: 'keyword.unsigned', foreground: '267f99' },
      { token: 'keyword.auto', foreground: '267f99' },
      { token: 'keyword.wchar_t', foreground: '267f99' },
      { token: 'type', foreground: '267f99' },
      { token: 'type.identifier', foreground: '267f99' },
      { token: 'identifier', foreground: '001080' },
      { token: 'entity.name.function', foreground: '795e26' },
      { token: 'entity.name.function.call', foreground: '795e26' },
      { token: 'support.function', foreground: '795e26' },
      { token: 'function', foreground: '795e26' },
      { token: 'variable', foreground: '001080' },
      { token: 'delimiter', foreground: '000000' }
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editorCursor.foreground': '#000000',
      'editor.lineHighlightBackground': '#f3f3f3',
      'editorLineNumber.foreground': '#6e7681',
      'editorLineNumber.activeForeground': '#000000',
      'editor.selectionBackground': '#add6ff',
      'editor.inactiveSelectionBackground': '#e5ebf1'
    }
  },

  'dracula': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'f8f8f2', background: '282a36' },
      { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6272a4', fontStyle: 'italic' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'string.escape', foreground: 'ffb86c' },
      { token: 'string.escape.invalid', foreground: 'ff5555' },
      { token: 'string.quote', foreground: 'f1fa8c' },
      { token: 'string.raw', foreground: 'f1fa8c' },
      { token: 'string.raw.begin', foreground: 'f1fa8c' },
      { token: 'string.raw.end', foreground: 'f1fa8c' },
      { token: 'string.include.identifier', foreground: 'f1fa8c' },
      { token: 'string.invalid', foreground: 'ff5555' },
      { token: 'character', foreground: 'f1fa8c' },
      { token: 'character.escape', foreground: 'ffb86c' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'number.hex', foreground: 'bd93f9' },
      { token: 'number.float', foreground: 'bd93f9' },
      { token: 'keyword', foreground: 'ff79c6', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'ff79c6', fontStyle: 'bold' },
      { token: 'keyword.directive', foreground: 'ff79c6' },
      { token: 'keyword.directive.include', foreground: 'ff79c6' },
      { token: 'keyword.int', foreground: '8be9fd' },
      { token: 'keyword.long', foreground: '8be9fd' },
      { token: 'keyword.char', foreground: '8be9fd' },
      { token: 'keyword.bool', foreground: '8be9fd' },
      { token: 'keyword.double', foreground: '8be9fd' },
      { token: 'keyword.float', foreground: '8be9fd' },
      { token: 'keyword.void', foreground: '8be9fd' },
      { token: 'keyword.auto', foreground: '8be9fd' },
      { token: 'identifier', foreground: '50fa7b' },
      { token: 'entity.name.function', foreground: '50fa7b' },
      { token: 'type', foreground: '8be9fd' },
      { token: 'type.identifier', foreground: '8be9fd' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'delimiter', foreground: 'f8f8f2' }
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editorCursor.foreground': '#aeafad',
      'editor.lineHighlightBackground': '#44475a55',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'editor.selectionBackground': '#44475a',
      'editor.inactiveSelectionBackground': '#44475a88'
    }
  },

  'one-dark-pro': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'abb2bf', background: '282c34' },
      { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '5c6370', fontStyle: 'italic' },
      { token: 'string', foreground: '98c379' },
      { token: 'string.escape', foreground: '56b6c2' },
      { token: 'string.escape.invalid', foreground: 'e06c75' },
      { token: 'string.quote', foreground: '98c379' },
      { token: 'string.raw', foreground: '98c379' },
      { token: 'string.raw.begin', foreground: '98c379' },
      { token: 'string.raw.end', foreground: '98c379' },
      { token: 'string.include.identifier', foreground: '98c379' },
      { token: 'string.invalid', foreground: 'e06c75' },
      { token: 'character', foreground: '98c379' },
      { token: 'character.escape', foreground: '56b6c2' },
      { token: 'number', foreground: 'd19a66' },
      { token: 'number.hex', foreground: 'd19a66' },
      { token: 'number.float', foreground: 'd19a66' },
      { token: 'keyword', foreground: 'c678dd' },
      { token: 'keyword.control', foreground: 'c678dd' },
      { token: 'keyword.directive', foreground: 'c678dd' },
      { token: 'keyword.directive.include', foreground: 'c678dd' },
      { token: 'keyword.int', foreground: 'e5c07b' },
      { token: 'keyword.long', foreground: 'e5c07b' },
      { token: 'keyword.char', foreground: 'e5c07b' },
      { token: 'keyword.bool', foreground: 'e5c07b' },
      { token: 'keyword.double', foreground: 'e5c07b' },
      { token: 'keyword.float', foreground: 'e5c07b' },
      { token: 'keyword.void', foreground: 'e5c07b' },
      { token: 'keyword.auto', foreground: 'e5c07b' },
      { token: 'identifier', foreground: '61afef' },
      { token: 'entity.name.function', foreground: '61afef' },
      { token: 'type', foreground: 'e5c07b' },
      { token: 'type.identifier', foreground: 'e5c07b' },
      { token: 'variable', foreground: 'e06c75' },
      { token: 'delimiter', foreground: 'abb2bf' }
    ],
    colors: {
      'editor.background': '#282c34',
      'editor.foreground': '#abb2bf',
      'editorCursor.foreground': '#528bff',
      'editor.lineHighlightBackground': '#2c313a',
      'editorLineNumber.foreground': '#4b5263',
      'editorLineNumber.activeForeground': '#abb2bf',
      'editor.selectionBackground': '#3e4451',
      'editor.inactiveSelectionBackground': '#3e445188'
    }
  },

  'github-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'c9d1d9', background: '0d1117' },
      { token: 'comment', foreground: '8b949e', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '8b949e', fontStyle: 'italic' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'string.escape', foreground: '79c0ff' },
      { token: 'string.escape.invalid', foreground: 'ff7b72' },
      { token: 'string.quote', foreground: 'a5d6ff' },
      { token: 'string.raw', foreground: 'a5d6ff' },
      { token: 'string.raw.begin', foreground: 'a5d6ff' },
      { token: 'string.raw.end', foreground: 'a5d6ff' },
      { token: 'string.include.identifier', foreground: 'a5d6ff' },
      { token: 'string.invalid', foreground: 'ff7b72' },
      { token: 'character', foreground: 'a5d6ff' },
      { token: 'character.escape', foreground: '79c0ff' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'number.hex', foreground: '79c0ff' },
      { token: 'number.float', foreground: '79c0ff' },
      { token: 'keyword', foreground: 'ff7b72', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'ff7b72', fontStyle: 'bold' },
      { token: 'keyword.directive', foreground: 'ff7b72' },
      { token: 'keyword.directive.include', foreground: 'ff7b72' },
      { token: 'keyword.int', foreground: 'ffa657' },
      { token: 'keyword.long', foreground: 'ffa657' },
      { token: 'keyword.char', foreground: 'ffa657' },
      { token: 'keyword.bool', foreground: 'ffa657' },
      { token: 'keyword.double', foreground: 'ffa657' },
      { token: 'keyword.float', foreground: 'ffa657' },
      { token: 'keyword.void', foreground: 'ffa657' },
      { token: 'keyword.auto', foreground: 'ffa657' },
      { token: 'identifier', foreground: 'd2a8ff' },
      { token: 'entity.name.function', foreground: 'd2a8ff' },
      { token: 'type', foreground: 'ffa657' },
      { token: 'type.identifier', foreground: 'ffa657' },
      { token: 'variable', foreground: 'c9d1d9' },
      { token: 'delimiter', foreground: 'c9d1d9' }
    ],
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#c9d1d9',
      'editorCursor.foreground': '#58a6ff',
      'editor.lineHighlightBackground': '#161b22',
      'editorLineNumber.foreground': '#484f58',
      'editorLineNumber.activeForeground': '#c9d1d9',
      'editor.selectionBackground': '#1f6feb44',
      'editor.inactiveSelectionBackground': '#1f6feb22'
    }
  },

  'monokai': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'f8f8f2', background: '272822' },
      { token: 'comment', foreground: '75715e', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '75715e', fontStyle: 'italic' },
      { token: 'string', foreground: 'e6db74' },
      { token: 'string.escape', foreground: 'ae81ff' },
      { token: 'string.escape.invalid', foreground: 'f92672' },
      { token: 'string.quote', foreground: 'e6db74' },
      { token: 'string.raw', foreground: 'e6db74' },
      { token: 'string.raw.begin', foreground: 'e6db74' },
      { token: 'string.raw.end', foreground: 'e6db74' },
      { token: 'string.include.identifier', foreground: 'e6db74' },
      { token: 'string.invalid', foreground: 'f92672' },
      { token: 'character', foreground: 'e6db74' },
      { token: 'character.escape', foreground: 'ae81ff' },
      { token: 'number', foreground: 'ae81ff' },
      { token: 'number.hex', foreground: 'ae81ff' },
      { token: 'number.float', foreground: 'ae81ff' },
      { token: 'keyword', foreground: 'f92672', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'f92672', fontStyle: 'bold' },
      { token: 'keyword.directive', foreground: 'f92672' },
      { token: 'keyword.directive.include', foreground: 'f92672' },
      { token: 'keyword.int', foreground: '66d9ef' },
      { token: 'keyword.long', foreground: '66d9ef' },
      { token: 'keyword.char', foreground: '66d9ef' },
      { token: 'keyword.bool', foreground: '66d9ef' },
      { token: 'keyword.double', foreground: '66d9ef' },
      { token: 'keyword.float', foreground: '66d9ef' },
      { token: 'keyword.void', foreground: '66d9ef' },
      { token: 'keyword.auto', foreground: '66d9ef' },
      { token: 'identifier', foreground: 'a6e22e' },
      { token: 'entity.name.function', foreground: 'a6e22e' },
      { token: 'type', foreground: '66d9ef' },
      { token: 'type.identifier', foreground: '66d9ef' },
      { token: 'variable', foreground: 'fd971f' },
      { token: 'delimiter', foreground: 'f8f8f2' }
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'editorCursor.foreground': '#f8f8f0',
      'editor.lineHighlightBackground': '#3e3d32',
      'editorLineNumber.foreground': '#90908a',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'editor.selectionBackground': '#49483e',
      'editor.inactiveSelectionBackground': '#49483e88'
    }
  },

  'catppuccin': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'cdd6f4', background: '1e1e2e' },
      { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6c7086', fontStyle: 'italic' },
      { token: 'string', foreground: 'a6e3a1' },
      { token: 'string.escape', foreground: 'f5c2e7' },
      { token: 'string.escape.invalid', foreground: 'f38ba8' },
      { token: 'string.quote', foreground: 'a6e3a1' },
      { token: 'string.raw', foreground: 'a6e3a1' },
      { token: 'string.raw.begin', foreground: 'a6e3a1' },
      { token: 'string.raw.end', foreground: 'a6e3a1' },
      { token: 'string.include.identifier', foreground: 'a6e3a1' },
      { token: 'string.invalid', foreground: 'f38ba8' },
      { token: 'character', foreground: 'a6e3a1' },
      { token: 'character.escape', foreground: 'f5c2e7' },
      { token: 'number', foreground: 'fab387' },
      { token: 'number.hex', foreground: 'fab387' },
      { token: 'number.float', foreground: 'fab387' },
      { token: 'keyword', foreground: 'cba6f7', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'cba6f7', fontStyle: 'bold' },
      { token: 'keyword.directive', foreground: 'cba6f7' },
      { token: 'keyword.directive.include', foreground: 'cba6f7' },
      { token: 'keyword.int', foreground: 'f9e2af' },
      { token: 'keyword.long', foreground: 'f9e2af' },
      { token: 'keyword.char', foreground: 'f9e2af' },
      { token: 'keyword.bool', foreground: 'f9e2af' },
      { token: 'keyword.double', foreground: 'f9e2af' },
      { token: 'keyword.float', foreground: 'f9e2af' },
      { token: 'keyword.void', foreground: 'f9e2af' },
      { token: 'keyword.auto', foreground: 'f9e2af' },
      { token: 'identifier', foreground: '89b4fa' },
      { token: 'entity.name.function', foreground: '89b4fa' },
      { token: 'type', foreground: 'f9e2af' },
      { token: 'type.identifier', foreground: 'f9e2af' },
      { token: 'variable', foreground: 'cdd6f4' },
      { token: 'delimiter', foreground: 'cdd6f4' }
    ],
    colors: {
      'editor.background': '#1e1e2e',
      'editor.foreground': '#cdd6f4',
      'editorCursor.foreground': '#f5e0dc',
      'editor.lineHighlightBackground': '#313244',
      'editorLineNumber.foreground': '#585b70',
      'editorLineNumber.activeForeground': '#cdd6f4',
      'editor.selectionBackground': '#45475a',
      'editor.inactiveSelectionBackground': '#45475a88'
    }
  }
};

if (typeof globalThis !== 'undefined') {
  globalThis.MONACO_THEMES = MONACO_THEMES;
}
